### GET
http://localhost:3003/api/blogs


###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "test",
  "author": "environment",
  "url": "lole",
  "likes": 11
}
###
PUT  http://localhost:3003/api/blogs/60e154f4cb088b1902ea83e6 HTTP/1.1
Content-Type: application/json

{
  "title": "okaynow",
  "author": "work",
  "url": "borasdfpa",
  "likes": 30
}

###
DELETE http://localhost:3003/api/blogs/60e154f4cb088b1902ea83e6 HTTP/1.1
